//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp_그림판.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharp_그림판.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] AnimatedGif {
            get {
                object obj = ResourceManager.GetObject("AnimatedGif", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] Microsoft_Win32_Primitives {
            get {
                object obj = ResourceManager.GetObject("Microsoft_Win32_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] netstandard {
            get {
                object obj = ResourceManager.GetObject("netstandard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_AppContext {
            get {
                object obj = ResourceManager.GetObject("System_AppContext", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Collections {
            get {
                object obj = ResourceManager.GetObject("System_Collections", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Collections_Concurrent {
            get {
                object obj = ResourceManager.GetObject("System_Collections_Concurrent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Collections_NonGeneric {
            get {
                object obj = ResourceManager.GetObject("System_Collections_NonGeneric", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Collections_Specialized {
            get {
                object obj = ResourceManager.GetObject("System_Collections_Specialized", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_ComponentModel {
            get {
                object obj = ResourceManager.GetObject("System_ComponentModel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_ComponentModel_EventBasedAsync {
            get {
                object obj = ResourceManager.GetObject("System_ComponentModel_EventBasedAsync", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_ComponentModel_Primitives {
            get {
                object obj = ResourceManager.GetObject("System_ComponentModel_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_ComponentModel_TypeConverter {
            get {
                object obj = ResourceManager.GetObject("System_ComponentModel_TypeConverter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Console {
            get {
                object obj = ResourceManager.GetObject("System_Console", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Data_Common {
            get {
                object obj = ResourceManager.GetObject("System_Data_Common", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Diagnostics_Contracts {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_Contracts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Diagnostics_Debug {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_Debug", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Diagnostics_FileVersionInfo {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_FileVersionInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Diagnostics_Process {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_Process", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Diagnostics_StackTrace {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_StackTrace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Diagnostics_TextWriterTraceListener {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_TextWriterTraceListener", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Diagnostics_Tools {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_Tools", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Diagnostics_TraceSource {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_TraceSource", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Diagnostics_Tracing {
            get {
                object obj = ResourceManager.GetObject("System_Diagnostics_Tracing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Drawing_Common {
            get {
                object obj = ResourceManager.GetObject("System_Drawing_Common", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Drawing_Primitives {
            get {
                object obj = ResourceManager.GetObject("System_Drawing_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Dynamic_Runtime {
            get {
                object obj = ResourceManager.GetObject("System_Dynamic_Runtime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Globalization {
            get {
                object obj = ResourceManager.GetObject("System_Globalization", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Globalization_Calendars {
            get {
                object obj = ResourceManager.GetObject("System_Globalization_Calendars", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Globalization_Extensions {
            get {
                object obj = ResourceManager.GetObject("System_Globalization_Extensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_IO {
            get {
                object obj = ResourceManager.GetObject("System_IO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_IO_Compression {
            get {
                object obj = ResourceManager.GetObject("System_IO_Compression", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_IO_Compression_ZipFile {
            get {
                object obj = ResourceManager.GetObject("System_IO_Compression_ZipFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_IO_FileSystem {
            get {
                object obj = ResourceManager.GetObject("System_IO_FileSystem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_IO_FileSystem_DriveInfo {
            get {
                object obj = ResourceManager.GetObject("System_IO_FileSystem_DriveInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_IO_FileSystem_Primitives {
            get {
                object obj = ResourceManager.GetObject("System_IO_FileSystem_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_IO_FileSystem_Watcher {
            get {
                object obj = ResourceManager.GetObject("System_IO_FileSystem_Watcher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_IO_IsolatedStorage {
            get {
                object obj = ResourceManager.GetObject("System_IO_IsolatedStorage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_IO_MemoryMappedFiles {
            get {
                object obj = ResourceManager.GetObject("System_IO_MemoryMappedFiles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_IO_Pipes {
            get {
                object obj = ResourceManager.GetObject("System_IO_Pipes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_IO_UnmanagedMemoryStream {
            get {
                object obj = ResourceManager.GetObject("System_IO_UnmanagedMemoryStream", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Linq {
            get {
                object obj = ResourceManager.GetObject("System_Linq", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Linq_Expressions {
            get {
                object obj = ResourceManager.GetObject("System_Linq_Expressions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Linq_Parallel {
            get {
                object obj = ResourceManager.GetObject("System_Linq_Parallel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Linq_Queryable {
            get {
                object obj = ResourceManager.GetObject("System_Linq_Queryable", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Net_Http {
            get {
                object obj = ResourceManager.GetObject("System_Net_Http", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Net_NameResolution {
            get {
                object obj = ResourceManager.GetObject("System_Net_NameResolution", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Net_NetworkInformation {
            get {
                object obj = ResourceManager.GetObject("System_Net_NetworkInformation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Net_Ping {
            get {
                object obj = ResourceManager.GetObject("System_Net_Ping", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Net_Primitives {
            get {
                object obj = ResourceManager.GetObject("System_Net_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Net_Requests {
            get {
                object obj = ResourceManager.GetObject("System_Net_Requests", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Net_Security {
            get {
                object obj = ResourceManager.GetObject("System_Net_Security", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Net_Sockets {
            get {
                object obj = ResourceManager.GetObject("System_Net_Sockets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Net_WebHeaderCollection {
            get {
                object obj = ResourceManager.GetObject("System_Net_WebHeaderCollection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Net_WebSockets {
            get {
                object obj = ResourceManager.GetObject("System_Net_WebSockets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Net_WebSockets_Client {
            get {
                object obj = ResourceManager.GetObject("System_Net_WebSockets_Client", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_ObjectModel {
            get {
                object obj = ResourceManager.GetObject("System_ObjectModel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Reflection {
            get {
                object obj = ResourceManager.GetObject("System_Reflection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Reflection_Extensions {
            get {
                object obj = ResourceManager.GetObject("System_Reflection_Extensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Reflection_Primitives {
            get {
                object obj = ResourceManager.GetObject("System_Reflection_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Resources_Reader {
            get {
                object obj = ResourceManager.GetObject("System_Resources_Reader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Resources_ResourceManager {
            get {
                object obj = ResourceManager.GetObject("System_Resources_ResourceManager", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Resources_Writer {
            get {
                object obj = ResourceManager.GetObject("System_Resources_Writer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Runtime {
            get {
                object obj = ResourceManager.GetObject("System_Runtime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Runtime_CompilerServices_VisualC {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_CompilerServices_VisualC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Runtime_Extensions {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_Extensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Runtime_Handles {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_Handles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Runtime_InteropServices {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_InteropServices", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Runtime_InteropServices_RuntimeInformation {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_InteropServices_RuntimeInformation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Runtime_Numerics {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_Numerics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Runtime_Serialization_Formatters {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_Serialization_Formatters", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Runtime_Serialization_Json {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_Serialization_Json", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Runtime_Serialization_Primitives {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_Serialization_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Runtime_Serialization_Xml {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_Serialization_Xml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Security_Claims {
            get {
                object obj = ResourceManager.GetObject("System_Security_Claims", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Security_Cryptography_Algorithms {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_Algorithms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Security_Cryptography_Csp {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_Csp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Security_Cryptography_Encoding {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_Encoding", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Security_Cryptography_Primitives {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_Primitives", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Security_Cryptography_X509Certificates {
            get {
                object obj = ResourceManager.GetObject("System_Security_Cryptography_X509Certificates", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Security_Principal {
            get {
                object obj = ResourceManager.GetObject("System_Security_Principal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Security_SecureString {
            get {
                object obj = ResourceManager.GetObject("System_Security_SecureString", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Text_Encoding {
            get {
                object obj = ResourceManager.GetObject("System_Text_Encoding", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Text_Encoding_Extensions {
            get {
                object obj = ResourceManager.GetObject("System_Text_Encoding_Extensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Text_RegularExpressions {
            get {
                object obj = ResourceManager.GetObject("System_Text_RegularExpressions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Threading {
            get {
                object obj = ResourceManager.GetObject("System_Threading", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Threading_Overlapped {
            get {
                object obj = ResourceManager.GetObject("System_Threading_Overlapped", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Threading_Tasks {
            get {
                object obj = ResourceManager.GetObject("System_Threading_Tasks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Threading_Tasks_Parallel {
            get {
                object obj = ResourceManager.GetObject("System_Threading_Tasks_Parallel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Threading_Thread {
            get {
                object obj = ResourceManager.GetObject("System_Threading_Thread", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Threading_ThreadPool {
            get {
                object obj = ResourceManager.GetObject("System_Threading_ThreadPool", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Threading_Timer {
            get {
                object obj = ResourceManager.GetObject("System_Threading_Timer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_ValueTuple {
            get {
                object obj = ResourceManager.GetObject("System_ValueTuple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Xml_ReaderWriter {
            get {
                object obj = ResourceManager.GetObject("System_Xml_ReaderWriter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Xml_XDocument {
            get {
                object obj = ResourceManager.GetObject("System_Xml_XDocument", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Xml_XmlDocument {
            get {
                object obj = ResourceManager.GetObject("System_Xml_XmlDocument", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Xml_XmlSerializer {
            get {
                object obj = ResourceManager.GetObject("System_Xml_XmlSerializer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Xml_XPath {
            get {
                object obj = ResourceManager.GetObject("System_Xml_XPath", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   System.Byte[] 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static byte[] System_Xml_XPath_XDocument {
            get {
                object obj = ResourceManager.GetObject("System_Xml_XPath_XDocument", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
